server:
  port: 8090
spring:
  application:
    name: spring-grpc-client

grpc:
  client:
    hello-service:
      address: static://localhost:9090
      negotiation-type: PLAINTEXT
      enable-keep-alive: true
      keep-alive-without-calls: true